name: Build and Lint

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
    
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # the Node.js versions to build on
        node-version: [16.x, 18.x, 20.x, 22.x, 24.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }} 
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Build the project
        run: yarn build
        env:
          CI: true
                   
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # the Node.js versions to build on
        node-version: [16.x, 18.x, 20.x, 22.x, 24.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }} 
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Lint the project
        run: yarn lint
        env:
          CI: true
